version: '3'
services:

  #Laravel App
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lionertic/chat:init
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  #Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./config_files/nginx/:/etc/nginx/conf.d/
    networks:
      - frontend
      - backend

  #Flask Service
  flask:
    build:
      context: ./
      dockerfile: ./Flask/Dockerfile
    image: lionertic/machine:init
    container_name: flask
    restart: always
    working_dir: /var/www/apache-flask/app/
    volumes:
      - ./Flask/app:/var/www/apache-flask/app/
    expose:
      - 80
    networks:
      - backend

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: newLogin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - login:/var/lib/mysql/
    networks:
      - backend

  #PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    expose:
      - 80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    volumes:
      - /sessions
    networks:
      - backend

#Docker Networks
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
#Volumes
volumes:
  login:
    driver: local
